a = input('Difgite algo: ')
print('O tipo primitivo desse valor é: ',type(a))
print('Só tem espeço? ',a.isspace())
print('É um número? ',a.isnumeric())
print('É alfabetico? ',a.isalpha())
print('É alfanumerico? ',a.isalnum())
print('Está em maiúscula? ',a.isupper())
print('Está em minúscula? ',a.islower())
print('Está captitalizada? ',a.istitle())